#### Handling Imbalanced Dataset with Machine Learnining

In [1]:
# Credit Card Fraud Detection || Kaggle

In [2]:
import pandas as pd
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [4]:
len(df.columns)

31

In [5]:
df.shape

(284807, 31)

In [6]:
df.isnull().sum().count()

31

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df.Class.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [9]:
df['V2'].value_counts()

V2
-0.326668    77
 0.166975    77
 0.089735    62
-0.606529    60
-0.146975    53
             ..
 0.432811     1
-0.504471     1
-1.210369     1
-0.395470     1
-0.189733     1
Name: count, Length: 275663, dtype: int64

In [26]:
# Independent and Dependent Feature
X  = df.drop('Class',axis =1)
y = df.Class

In [19]:
# cross Validation like KFOLD and Hyperparameter tunning
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [21]:
10.0**np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [22]:
np.arange(-2,3)

array([-2, -1,  0,  1,  2])

In [23]:
10.0**(-2)

0.01

In [43]:
log_class = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv = KFold(n_splits = 5,random_state  = None,shuffle= False)

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.7)

In [45]:
clf = GridSearchCV (log_class,grid,cv=cv,n_jobs=-1,scoring = 'f1_macro')

In [36]:
clf

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['11', '12']},
             scoring='f1_macro')

In [38]:
X_test.shape

(85443, 30)

In [39]:
X_train.shape

(199364, 30)

In [47]:
clf.fit(X_train,y_train)

C:\Users\bikas\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\bikas\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\bikas\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\bikas\AppData\Local\Programs\Python\Python39\lib\site-packages\sk

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [50]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("\n")
print(accuracy_score(y_test,y_pred))
print("\n")
print(classification_report(y_test,y_pred))

[[85263    44]
 [   38    98]]


0.9990402958697612


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.69      0.72      0.71       136

    accuracy                           1.00     85443
   macro avg       0.84      0.86      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [55]:
print(X_train.shape)
print(y_train.value_counts())

(199364, 30)
Class
0    199008
1       356
Name: count, dtype: int64


In [59]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [56]:
class_weight = dict({0:1,1:100})
classifier = RandomForestClassifier(class_weight = class_weight)

NameError: name 'RandomForestClassifier' is not defined

In [61]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85297    10]
 [   29   107]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.91      0.79      0.85       136

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [62]:
## Under Sampling
y_train.value_counts()

Class
0    199008
1       356
Name: count, dtype: int64

In [63]:
from collections import Counter

In [64]:
from imblearn.under_sampling import NearMiss

In [70]:
ns = NearMiss()

In [71]:
X_train_ns,y_train_ns = ns.fit_sample(X_train,y_train)
print("The number of classes before fit{}".format(Counter(y_train)))
print("The numer of classes after fit{}".format(Counter(y_train_ns)))

AttributeError: 'NearMiss' object has no attribute 'fit_sample'